version: "3.8"

services:
  nginx_proxy:
    image: nginx:1.25.1-alpine
    container_name: nginx_proxy
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - corp

  node_server:
    container_name: node_server
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    networks:
      - corp

networks:
  corp:
    driver: bridge
